apiVersion: v1
kind: Service
metadata:
  name: "sv1"
spec:
  type: "LoadBalancer"
  ports:
  - port: 80
    targetPort: 5000


    protocol: TCP
  sessionAffinity: "ClientIP"
  selector:
    app: flask-final
