apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: git@github.com:babayaga-creator/dev-cicd-final
      sshPrivateKeySecret:
        name: final-dance
        key: sshPrivateKey
