apiVersion: v1

kind: PersistentVolume

metadata:

  name: flask-storage

  labels:

   type: local

spec:

  storageClassName: local-path

  capacity:

   storage: 1Gi

  accessModes:

   - ReadWriteOnce

  hostPath:

   path: "/home/arif/Desktop/pv"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-storage
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-final
  labels:
    app: flask-final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-final

  template:
    metadata:
      labels:
        app: flask-final


    spec:
      terminationGracePeriodSeconds: 1
      volumes:
        - name: flask-volume
          persistentVolumeClaim:
            claimName: flask-storage

      containers:
      - name: flask-image

        image: ghcr.io/babayaga-creator/dev-cicd-final/final_flask:V1.2.7

        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        volumeMounts:
        - name: flask-volume
          mountPath: /mnt/
        env:
        - name: MYSQL_HOST
          value: mysql.final.svc.cluster.local
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret

              key: mysql-user

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password

        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-database
      imagePullSecrets:
      - name: regcred
