name: Final Dance

on:
  workflow_dispatch:
  push:

jobs:
  out-docker-job:
    runs-on: "ubuntu-latest"
    steps:

      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "::set-output name=short_sha::$calculatedSha"

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/babayaga-creator/final_flask:${{ github.ref_name }}-${{ steps.vars.outputs.short_sha }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.TOKEN }}


      - uses: cschleiden/replace-tokens@v1
        with:
          files: '["manifests/flask/*.yml"]'
          tokenPrefix: __ # optional, default is #{
          tokenSuffix: __ # optional, default is }#
        env:
          IMAGE_NAME: "ghcr.io/babayaga-creator/final_flask:"
          IMAGE_TAG: ${{ steps.vars.outputs.short_sha }}

      - uses: azure/login@v1
        with:

          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/aks-set-context@v3
        with:
          resource-group: aks
          cluster-name: final-task
